---
- name: install packages
  with_items: "{{ postgresql_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart postgresql

- name: enable postgresql service
  template:
    src: postgresql.j2
    dest: /etc/rc.conf.d/postgresql
  notify:
    - restart postgresql

- name: initialize DB
  command: service postgresql initdb
  args:
    creates: "/var/db/postgres/data{{ postgresql_version }}"
    warn: False

- name: configure pg_hba
  template:
    src: pg_hba.conf.j2
    dest: /var/db/postgres/data{{ postgresql_version }}/pg_hba.conf
  notify:
    - restart postgresql

- name: configure postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /var/db/postgres/data{{ postgresql_version }}/postgresql.conf
  notify:
    - restart postgresql

- name: create wal directory
  file:
    path: /var/cache/postgresql
    owner: postgres
    group: postgres
    state: directory
  notify:
    - restart postgresql

- name: start service
  service:
    name: postgresql
    state: started
